variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

services:
  - docker:dind

build:
  stage: build
  tags:
    - docker
  script:
    - docker info
    - echo "Logging in to Docker registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Building Docker Image..."
    - docker build --tag $CI_REGISTRY_IMAGE:latest .
    - echo "Pushing Image to Registry!"
    - docker push $CI_REGISTRY_IMAGE:latest
